### ISSUE TITLE
Is anyone able to add run / build instructions?

### ISSUE THREAD

**Issue by christopher-caldwell** [runelite/example-plugin#10]
I'm rather a noob, and have no idea how to use this example. Is there anyway to add installation, running, usage instructions? Preferably more verbose than required.

**Comment by raiyni** [comment]
https://github.com/runelite/plugin-hub has the instructions in the readme.

**Comment by christopher-caldwell** [comment]
Why not put this link in the readme?

**Comment by Nightfirecat** [comment]
The readme is already linked from this repository, and generally speaking you should only have gotten to this repo from being linked from said readme.
