### ISSUE TITLE
suggestion: Change log.info in example plugin to log.debug

### ISSUE THREAD

**Issue by jammy-dodgers** [runelite/example-plugin#12]
It'd probably save time for people who aren't aware of log.info's pitfalls (https://github.com/runelite/plugin-hub/pull/3677#issuecomment-1378048431)

**Comment by Nightfirecat** [comment]
It's only logged at plugin startup and shutdown, which is very infrequent, so not really an issue. `log.info()` isn't forbidden by any means, but it's often misused by hub developers who don't consider that user logs get spammed.
